### ISSUE TITLE
KeyValueIterator refinements

### ISSUE THREAD

**Issue by btc** [ysono/pancake#6]
https://github.com/ysono/pancake/pull/5#issuecomment-882712860

> In contrast, another kind of "iterator" could be a coroutine that passes control back to the caller after every item (ie key or value). We can think about this later too.

@ysono I'm curious. Tell me more.

I also saw your note about avoiding extra work in `SSTable::search`. It would be interesting to decode values lazily.

**Comment by ysono** [comment]
Currently `KeyValueIterator` is being used in these ways:

- Read commit log, upon initialization
- Compact SSTables
- Range query

In the first use case we do want to read all keys and all values into memory. Commit log file is unsorted, and we can move forward only in a file, so we don't know till later whether the currently read value will be overwritten.

The last two use cases benefit from an "iterator" that does not always read file content into memory -- specifically file content corresponding to values. While doing k-merge, we have to read all keys, but we can determine whether values can be skipped. So we'd like an "iterator" that a) always reads the next key and b) either reads the next value or skips it. I'm not certain this can be done with vanilla std::iter and itertools concepts. We might have to use a heap manually: https://github.com/rust-itertools/itertools/blob/v0.10.1/src/kmerge_impl.rs#L174

> It's worth benchmarking to determine the cost associated with deserialization. With respect to inducing latency, it might be tiny compared to other costs (such as disk accesses).
> With respect to CPU cycles, it might be significant. But worth measuring when contemplating decisions that treat the cost as a material constraint which ought to influence code organization and system architecture.
(by @btc)

Fair point. There are so many ways to optimize, we want to pick our battles.

**Comment by ysono** [comment]
Done in https://github.com/ysono/pancake/commit/e776510d11beafd3626e3f95a7359b6df769f5d3
