### ISSUE TITLE
Secondary index

### ISSUE THREAD

**Issue by ysono** [ysono/pancake#9]
It'd be cool to apply the same storage engine to a secondary index.

The initial simplest design possible:
- Cover all data in the db. No targeted sub-group of data.
- Let the key be the first byte of each value. We'll keep the value byte-array only. No user-defined index.

With the above design, there is one secondary index and one primary index.

Impl:
- Synchronize the primary and secondary indexes.
- (what else?)

**Comment by btc** [comment]
What is the use case for a secondary index?

**Comment by ysono** [comment]
For learning :) It would make sense only if had structured data in our api. I want to verify my understanding that secondary indexes use the same storage engine structure, only with diff of:
- it's mapping from key to a specific sstable file and offset
- the same key may be multiple targets associated (unless it's a unique index)

**Comment by btc** [comment]
> For learning :) 

oh def! to clarify, i meant how is a secondary index used typically. like... i don't really have experience or an intuition of how real-world secondary indexes are used. all good

**Comment by ysono** [comment]
When we have `select whatever from mytable where col1 = val1`, the query would be inefficient if there is no index on `col1`.

I believe the query pattern and index(es) don't have to match exactly. If some index(es) cover a subset or superset of columns being queried, that's still better than not having any secondary index. In general.

The concept applies to non-relational too. Cf. https://redis.io/topics/indexes , https://docs.mongodb.com/manual/core/timeseries/timeseries-secondary-index/

**Comment by btc** [comment]
ah wow. very cool

**Comment by ysono** [comment]
![Primary (2)](https://user-images.githubusercontent.com/5148696/127942770-0d0cddc8-d80d-456a-bd38-9d492eb8faf8.png)
![Secondary (4)](https://user-images.githubusercontent.com/5148696/127942978-d78b293e-aade-45ca-b685-c1e2e5862450.png)


Some design diagrams. Let me know what you think.

Separated into 2 files only because of LucidChart's limitations on free accounts. Originals: https://lucid.app/lucidchart/21f96dd4-abfc-4f2e-8837-84da34aadd14/edit?beaconFlowId=E430E4E4095A0775&page=0_0# and https://lucid.app/lucidchart/7831fc4a-6e69-4399-9646-493a9567968b/edit?beaconFlowId=01D6A21A7FDA2A6A&page=0_0#

**Comment by btc** [comment]
Beautiful diagrams. 

How does code re-use work? Does it introduce any new structs? Does the `LSM` become something that is used multiple times inside of a larger structure?

How does a user command the DB to create and maintain a secondary index? Is it opt-in?

**Comment by ysono** [comment]
Good points. I wish we could reuse LSM tree. But it seems the secondary index structure is different in several ways. I'm introducing a `SecondaryIndex` struct, and it's used by all secondary indexes.

Yeah secondary indexes are opt in. They are created by `create index ...` sql. Client doesn't need to maintain it as far as I can see. You can `drop index`.

**Comment by btc** [comment]
> Good points. I wish we could reuse LSM tree. But it seems the secondary index structure is different in several ways. I'm introducing a SecondaryIndex struct, and it's used by all secondary indexes.

Sounds good! I suppose the SSTable gets some reuse. Is the file format different for the secondary SSTables?

**Comment by ysono** [comment]
Yep SSTable gets reused. I was just able to make it generic. The byte-wise file format is the same but the serialized contents are different.

Primary:
```
(primary key, primary value)
(primary key, primary value)
(primary key, primary value)
...
```

Secondary:
```
(sub-datum, pointer to primary index's sstable and offset thereof)
(sub-datum, pointer to primary index's sstable and offset thereof)
(sub-datum, pointer to primary index's sstable and offset thereof)
...
```

**Comment by ysono** [comment]
In this first impl (https://github.com/ysono/pancake/pull/52), the index usage is simplifed from the above diagram. Now, each secondary index is an independent LSMTree, and there is no longer a dependency between each secondary index's Vec<SSTables> and the primary index's Vec<SSTables>. The solution stores a mapping of `{ (sub-portion of value, key) : existence }` in each sec idx's LSMTree.

Another possible use of independent LSMTrees is to map `{ sub-portion of value : list< key > }`. But for the same key (which is `sub-portion of value`), we would need to merge the values (which are multiple instances of `list< key >`), and this complicates logic. So the above seems the way to go.

Also, I'm going to use this stream to upload diagrams, taking advantage of github's free CDN. These will be referred by rustdoc.

![Primary (3)](https://user-images.githubusercontent.com/5148696/128642691-55eea319-05a4-43bf-a2f9-13e9f5132a74.png)

![range query (1)](https://user-images.githubusercontent.com/5148696/128660102-e6da6e45-b6a1-4a2b-b038-66af51f212c7.png)

**Comment by ysono** [comment]
First done here https://github.com/ysono/pancake/commit/3943f31780df9183d9e5d8b697251294196ab4cb. Many improvements later.
